create extension if not exists pgcrypto;

create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, display_name text not null, bio text, avatar_url text, reviewer_points integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.tapes (id uuid primary key default gen_random_uuid(), artist_id uuid not null references public.profiles(id) on delete cascade, title text not null, description text, genre text, status text not null default 'draft' check (status in ('draft','published','archived')), audio_url text, artwork_url text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.reviews (id uuid primary key default gen_random_uuid(), tape_id uuid not null references public.tapes(id) on delete cascade, reviewer_id uuid not null references public.profiles(id) on delete cascade, status text not null default 'draft' check (status in ('draft','submitted','published','flagged')), recommendation text, submitted_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(tape_id, reviewer_id));
create table if not exists public.review_answers (id uuid primary key default gen_random_uuid(), review_id uuid not null references public.reviews(id) on delete cascade, step integer not null check (step between 1 and 5), question_key text not null, answer text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(review_id, question_key));
create table if not exists public.review_scores (id uuid primary key default gen_random_uuid(), review_id uuid not null references public.reviews(id) on delete cascade, songwriting integer check (songwriting between 1 and 10), performance integer check (performance between 1 and 10), production integer check (production between 1 and 10), clarity integer check (clarity between 1 and 10), improvement_area text, created_at timestamptz not null default now(), unique(review_id));
create table if not exists public.review_helpfulness (review_id uuid not null references public.reviews(id) on delete cascade, voter_id uuid not null references public.profiles(id) on delete cascade, helpful boolean not null, created_at timestamptz not null default now(), primary key(review_id,voter_id));
create table if not exists public.review_reports (id uuid primary key default gen_random_uuid(), review_id uuid not null references public.reviews(id) on delete cascade, reporter_id uuid not null references public.profiles(id) on delete cascade, reason text not null, created_at timestamptz not null default now(), unique(review_id,reporter_id));
create table if not exists public.subscriptions (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, stripe_customer_id text, stripe_subscription_id text, status text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(user_id));

alter table public.profiles enable row level security; alter table public.tapes enable row level security; alter table public.reviews enable row level security; alter table public.review_answers enable row level security; alter table public.review_scores enable row level security; alter table public.review_helpfulness enable row level security; alter table public.review_reports enable row level security; alter table public.subscriptions enable row level security;

create policy "public profiles readable" on public.profiles for select using (true);
create policy "users manage own profile" on public.profiles for all using (auth.uid()=id) with check (auth.uid()=id);
create policy "published tapes readable" on public.tapes for select using (status='published' or auth.uid()=artist_id);
create policy "artists manage own tapes" on public.tapes for all using (auth.uid()=artist_id) with check (auth.uid()=artist_id);
create policy "reviewers read own reviews" on public.reviews for select using (auth.uid()=reviewer_id or exists(select 1 from public.tapes t where t.id=tape_id and t.artist_id=auth.uid()));
create policy "reviewers create own reviews" on public.reviews for insert with check (auth.uid()=reviewer_id and not exists(select 1 from public.tapes t where t.id=tape_id and t.artist_id=auth.uid()));
create policy "reviewers update own reviews" on public.reviews for update using (auth.uid()=reviewer_id) with check (auth.uid()=reviewer_id);
create policy "reviewers manage own answers" on public.review_answers for all using (exists(select 1 from public.reviews r where r.id=review_id and r.reviewer_id=auth.uid())) with check (exists(select 1 from public.reviews r where r.id=review_id and r.reviewer_id=auth.uid()));
create policy "review scores access" on public.review_scores for all using (exists(select 1 from public.reviews r where r.id=review_id and (r.reviewer_id=auth.uid() or exists(select 1 from public.tapes t where t.id=r.tape_id and t.artist_id=auth.uid()))));
create policy "helpfulness access" on public.review_helpfulness for all using (auth.uid()=voter_id) with check (auth.uid()=voter_id);
create policy "reporters manage own reports" on public.review_reports for all using (auth.uid()=reporter_id) with check (auth.uid()=reporter_id);
create policy "users read own subscription" on public.subscriptions for select using (auth.uid()=user_id);

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,display_name) values(new.id,coalesce(new.raw_user_meta_data->>'display_name',split_part(new.email,'@',1))); return new; end; $$;
create or replace trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
